# Generated by Django 6.0.5 on 2026-05-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_id', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('is_online', models.BooleanField(default=True)),
                ('is_recording', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KandangSapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('population', models.IntegerField(default=0)),
                ('healthy', models.IntegerField(default=0)),
                ('sick', models.IntegerField(default=0)),
                ('temp', models.FloatField(default=0)),
                ('ammonia', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KeranIrigasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valve_id', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('is_open', models.BooleanField(default=False)),
                ('flow_rate', models.FloatField(default=0)),
                ('pressure', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KolamBioflok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pond_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('ph', models.FloatField(default=7.0)),
                ('do_level', models.FloatField(default=5.0)),
                ('temp', models.FloatField(default=28.0)),
                ('ammonia', models.FloatField(default=0.1)),
                ('biofloc_status', models.CharField(default='Baik', max_length=20)),
                ('aerator_on', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LampuJalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_id', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('is_on', models.BooleanField(default=False)),
                ('brightness', models.IntegerField(default=0)),
                ('watt', models.IntegerField(default=30)),
                ('is_fault', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ZonePertanian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('moisture', models.FloatField(default=0)),
                ('temp', models.FloatField(default=0)),
                ('ph', models.FloatField(default=0)),
                ('npk_status', models.CharField(default='Normal', max_length=50)),
                ('irrig_on', models.BooleanField(default=False)),
            ],
        ),
    ]
