# Generated by Django 6.0.5 on 2026-05-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctv',
            name='stream_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
