# Generated by Django 6.0.5 on 2026-05-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_cctv_stream_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesjid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesjid_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_speaker_on', models.BooleanField(default=False)),
                ('is_ac_on', models.BooleanField(default=False)),
                ('temp', models.FloatField(default=28.0)),
                ('power_usage', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PosRonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_online', models.BooleanField(default=True)),
                ('is_sorot_on', models.BooleanField(default=False)),
                ('is_alarm_active', models.BooleanField(default=False)),
                ('last_patrol', models.CharField(default='-', max_length=20)),
            ],
        ),
    ]
